### ISSUE TITLE
`-language` options are not in any of the common options traits

### ISSUE THREAD

**Issue by DavidGregory084** [nafg/scalac-options#34]
Language imports were added in Scala 2.10, but I am not sure when they were added as scalac options.

In sbt-tpolecat, with the exception of `existentials` which is disabled for 3.x they are added regardless of Scala version.

I have noticed that when trying to use the DSL to set `-language` options that there is no common option set which contains them.

They appear in `V2_12`:

```scala
  /**
   * Enable or disable language features: `_' for all, `-language:help' to list choices.
   */
  def language(`_,feature,-feature`: String) = List("-language:" + `_,feature,-feature`)
```

They don't appear to have been parsed correctly in `V3`:

```scala
  /**
   * Enable one or more language features.
   */
  def language = List("-language")
```

**Comment by nafg** [comment]
Releasing as 0.2.0 https://github.com/nafg/scalac-options/actions/runs/2049523936
